FROM python:3.9.13-slim-buster

WORKDIR /app

LABEL maintainer="stianalise@gmail.com"
LABEL description="Development image for the Hospitals GeoDjango API"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update \
    && apt install -y netcat gcc postgresql \
    && apt clean

RUN apt update \
    && apt install -y binutils libproj-dev gdal-bin python-gdal python3-gdal

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app