version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres-db
    networks:
      - hospital-api

  postgres-db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5454:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    restart: "on-failure"
    networks:
      - hospital-api

  nginx:
    restart: always
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    networks:
      - hospital-api

networks:
  hospital-api:
    driver: bridge

volumes:
  postgres_data: