# Generated by Django 4.1.7 on 2023-02-22 01:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boundaries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boundary",
            name="mpoly",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
